// react/src/ColumnComponent.jsx
import { uuid } from "@jsplumbtoolkit/browser-ui"

/**
 * Component for a column in the Kanban
 */
export default function ColumnComponent({ctx}) {

    function addItem(event) {
        if (event.code === "Enter") {

            // On enter keypress, find out how many members there already are in the column
            const order = ctx.vertex.getMembers().length
            // add a new item to the column, specifying an `order` property and the text from
            // the input field, or default to `Item` if the user didnt type anything.
            const node = ctx.toolkit.addNode({
                group:ctx.vertex.id,
                id:uuid(),
                order,
                name:event.target.value || "Item"
            })

            // show the rendered item in the next tick of the event loop
            setTimeout(() => {
                const el = ctx.surface.getRenderedElement(node)
                el.scrollIntoView()
                ctx.toolkit.setSelection(node)
            }, 0)

            // clear the input field
            event.target.value = ""

        }
    }

    return <div className="jtk-kanban-lane">
        <div className="jtk-kanban-lane-header">

            <div className="jtk-kanban-lane-titlebar">
                <div className="jtk-kanban-lane-color" style={{ "backgroundColor":ctx.vertex.data.color}}/>
                <div className="jtk-kanban-lane-title">{ctx.vertex.data.title}</div>
                <div className="jtk-kanban-lane-edit" onClick={() => ctx.toolkit.setSelection(ctx.vertex)}/>
            </div>

            <div className="jtk-kanban-lane-description">{ctx.vertex.data.description}</div>
        </div>

        { /* the items go into this element */ }
        <div data-jtk-group-content="true"/>

        <div className="jtk-kanban-lane-footer">
            <input type="text" placeholder="Add item..." onKeyPress={(e) => addItem(e)}/>
        </div>
    </div>
}

// angular/src/app/column.component.ts
import {Component} from "@angular/core"
import {BaseNodeComponent} from "@jsplumbtoolkit/browser-ui-angular"
import { uuid, Group} from "@jsplumbtoolkit/browser-ui"

@Component({
  template:`<div class="jtk-kanban-lane">
                        <div class="jtk-kanban-lane-header">
                        
                        <div class="jtk-kanban-lane-titlebar">
                            <div class="jtk-kanban-lane-color" style="background-color: {{obj.color}}"></div>
                            <div class="jtk-kanban-lane-title">{{obj.title}}</div>
                            <div class="jtk-kanban-lane-edit" (click)="editColumn()"></div>
                        </div>
                        
                        <div class="jtk-kanban-lane-description">{{obj.description}}</div>
                        </div>
                        
                        <div data-jtk-group-content="true"></div>
                        <div class="jtk-kanban-lane-footer">
                            <input type="text" placeholder="Add item..." (keypress)="maybeAddItem($event)">
                        </div>
                    </div>
  `
})
export class ColumnComponent extends BaseNodeComponent{


  editColumn() {
    this.toolkit.setSelection(this.getNode())
  }

  maybeAddItem(event:KeyboardEvent) {
    if (event.keyCode === 13) {
      const target = event.target as HTMLInputElement
      const group = (this.getNode() as Group)
      const order = group.getMembers().length
      const node = this.toolkit.addNode({
        group:group.id,
        id:uuid(),
        order,
        name:target.value || "Item"
      })
      const el = this.surface.getRenderedElement(node)
      el.scrollIntoView()
      this.toolkit.setSelection(node)

      target.value = ""
    }
  }

}
