// react/src/InspectorComponent.jsx
import React, {useState} from "react";

import {InspectorComponent} from "@jsplumbtoolkit/browser-ui-react"
import { Node, Group } from "@jsplumbtoolkit/browser-ui"

export default function KanbanInspectorComponent() {

    const [currentType, setCurrentType] = useState('')

    return <InspectorComponent renderEmptyContainer={() => setCurrentType('')} refresh={(obj,cb) => setCurrentType(obj.objectType)}>

        { currentType === '' && <></> }

        { currentType === Node.objectType &&
        <div className="jtk-kanban-inspector">
            <strong>Label</strong>
            <input jtk-att="name" type="text"/>
            <strong>Description</strong>
            <textarea jtk-att="description" rows="10"/>
            </div>
        }

        { currentType === Group.objectType &&
        <div className="jtk-kanban-inspector">
            <strong>Title</strong>
            <input jtk-att="title" type="text"/>
            <strong>Description</strong>
            <textarea jtk-att="description" rows="10"/>
            <strong>Color</strong>
            <input type="color" jtk-att="color"/>
        </div>
        }

    </InspectorComponent>

}

// angular/src/app/inspector.component.ts
import {Component} from "@angular/core"
import {InspectorComponent} from "@jsplumbtoolkit/browser-ui-angular"
import { Node, Group } from "@jsplumbtoolkit/browser-ui"

@Component({
    template:`<div class="inspector">
      
      @if(currentType === NODE) {
        <div class="jtk-kanban-inspector">
            <strong>Label</strong>
            <input jtk-att="name" type="text">
            <strong>Description</strong>
          <textarea jtk-att="description" rows="10"></textarea>
        </div>
      }  

      @if(currentType === GROUP) {
        <div class="jtk-kanban-inspector">
          <strong>Title</strong>
          <input jtk-att="title" type="text">
          <strong>Description</strong>
          <textarea jtk-att="description" rows="10"></textarea>
          <strong>Color</strong>
          <input type="color" jtk-att="color">
  
        </div>
      }  
      
    </div>`,
    selector:"app-inspector"
})
export class KanbanInspectorComponent extends InspectorComponent {
  NODE = Node.objectType
  GROUP = Group.objectType
}
