// react/src/Kanban.jsx
import { useRef, useEffect } from 'react'
import { createRoot } from "react-dom/client";

import { JsPlumbToolkitSurfaceComponent } from "@jsplumbtoolkit/browser-ui-react"
import { EVENT_TAP, EmptyLayout, uuid, newInstance, RowLayout, EVENT_CANVAS_CLICK } from "@jsplumbtoolkit/browser-ui"

import ColumnComponent from './ColumnComponent'
import ItemComponent from './ItemComponent'
import { DragManager } from './drag-manager'
import Inspector from './InspectorComponent'

export default function Kanban(props) {

    const toolkit = newInstance()
    const initialized = useRef(null)
    const surfaceRef = useRef(null)
    const inspectorContainer = useRef(null)

    const view = {
        nodes:{
            default:{
                jsx:(ctx) => <ItemComponent ctx={ctx} />,
                events:{
                    [EVENT_TAP]:(p) => {
                        toolkit.setSelection(p.obj)
                    }
                }
            }
        },
        groups: {
            default: {
                jsx:(ctx) => <ColumnComponent ctx={ctx}/>,
                layout:{
                    type:EmptyLayout.type
                },
                events:{
                    [EVENT_TAP]:(p) => {
                        toolkit.clearSelection()
                    }
                }

            }
        }
    }

    const renderParams = {
        layout:{
            type:RowLayout.type,
            options:{
                padding:{x:10, y:0}
            }
        },
        dragOptions:{
            filter:"*"
        },
        wheel:{
            zoom:false
        },
        events:{
            [EVENT_CANVAS_CLICK]:() => toolkit.clearSelection()
        },
        consumeRightClick:false
    }

    function addColumn(event) {
        if (event.code === "Enter") {
            debugger
            const column = toolkit.addGroup({
                id:uuid(),
                title:event.target.value,
                description:"",
                color:"#FFFFFF"
            })
            event.target.value = ""
            const el = surfaceRef.current.surface.getRenderedElement(column)
            el.scrollIntoView()
        }
    }

    useEffect(() => {
        if (!initialized.current) {
            initialized.current = true

            new DragManager(surfaceRef.current.surface)

            const ic = createRoot(inspectorContainer.current)
            ic.render(<Inspector surface={surfaceRef.current.surface} container={inspectorContainer.current}/>)

            toolkit.load({
                url:'/public/dataset.json'
            })
        }
    })

    return <div className="jtk-kanban-main">
            <div className="jtk-kanban-container">
                <JsPlumbToolkitSurfaceComponent 
                    view={view}
                    renderParams={renderParams} 
                    ref={surfaceRef}
                    toolkit={toolkit}
                    />
            </div>

            <div className="jtk-kanban-rhs">

                <div id="controls">
                    <input type="text" id="txtAddColumn" placeholder="Add column..." onKeyPress={(e) => addColumn(e)}/>
                </div>

                <div id="inspector" ref={inspectorContainer}/>

                <div className="description">

                </div>
            </div>

        </div>

}

// angular/src/app/kanban.component.ts
import {AfterViewInit, Component, Input, ViewChild} from "@angular/core"
import {EVENT_CANVAS_CLICK, EVENT_TAP, RowLayout, Surface, uuid, Node, EmptyLayout} from "@jsplumbtoolkit/browser-ui"
import {AngularRenderOptions, BrowserUIAngular, jsPlumbSurfaceComponent} from "@jsplumbtoolkit/browser-ui-angular"
import {ItemComponent} from "./item.component"
import {ColumnComponent} from "./column.component"
import {DragManager} from "./drag-manager"

@Component({
  selector:`jtk-kanban`,
  template:`
    <div class="jtk-kanban-container">
      <jsplumb-surface [surfaceId]="kanbanId"
                       [toolkitId]="kanbanId"
                       [view]="view"
                       [renderParams]="renderParams">
  
      </jsplumb-surface>
    </div>
    <div class="jtk-kanban-rhs">
      <div id="controls">
        <input type="text" id="txtAddColumn" placeholder="Add column..." (keypress)="addColumn($event)">
      </div>
      <!-- node/group inspector -->
      <app-inspector [surfaceId]="kanbanId"></app-inspector>  
    </div>`
})
export class KanbanComponent implements AfterViewInit {

  @Input() kanbanId!:string

  @ViewChild(jsPlumbSurfaceComponent) surfaceComponent!:jsPlumbSurfaceComponent;
  toolkit!:BrowserUIAngular
  surface!:Surface

  renderParams:AngularRenderOptions = {
    layout:{
      type:RowLayout.type,
      options:{
        padding:{x:10, y:0}
      }
    },
    dragOptions:{
      filter:"*"
    },
    wheel:{
      zoom:false
    },
    events:{
      [EVENT_CANVAS_CLICK]:() => this.toolkit.clearSelection()
    },
  }

  view = {
    nodes: {
      default: {
        component:ItemComponent,
        events:{
          [EVENT_TAP]:(p:{obj:Node}) => {
            this.toolkit.setSelection(p.obj)
          }
        }
      }
    },
    groups: {
      default: {
        component:ColumnComponent,
        layout:{
          type:EmptyLayout.type
        },
        events:{
          [EVENT_TAP]:(p:any) => {
            this.toolkit.clearSelection()
          }
        }

      }
    }
  }

  ngAfterViewInit(): void {
    this.toolkit = this.surfaceComponent.surface.toolkitInstance
    this.surface = this.surfaceComponent.surface

    new DragManager(this.surface)

    this.toolkit.load({
      url:'/assets/dataset.json'
    })
  }

  addColumn(event:KeyboardEvent) {
    const target = event.target as HTMLInputElement
    if (event.keyCode === 13) {
      const column = this.toolkit.addGroup({
        id:uuid(),
        title:target.value,
        description:"",
        color:"#FFFFFF"
      })
      target.value = ""
      const el = this.surface.getRenderedElement(column)
      el.scrollIntoView()
    }
  }

}
